/*
Devcloud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// DevcloudPort struct for DevcloudPort
type DevcloudPort struct {
	Description   *string                 `json:"description,omitempty"`
	InterfaceMode *string                 `json:"interface_mode,omitempty"`
	LinkStatus    *string                 `json:"link_status,omitempty"`
	Mode          *string                 `json:"mode,omitempty"`
	NativeVlan    *DevcloudPortNativeVlan `json:"native_vlan,omitempty"`
	Port          *string                 `json:"port,omitempty"`
	TrunkGroups   *string                 `json:"trunk_groups,omitempty"`
	UntaggedVlan  *DevcloudPortNativeVlan `json:"untagged_vlan,omitempty"`
}

// NewDevcloudPort instantiates a new DevcloudPort object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDevcloudPort() *DevcloudPort {
	this := DevcloudPort{}
	return &this
}

// NewDevcloudPortWithDefaults instantiates a new DevcloudPort object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDevcloudPortWithDefaults() *DevcloudPort {
	this := DevcloudPort{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *DevcloudPort) GetDescription() string {
	if o == nil || isNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DevcloudPort) GetDescriptionOk() (*string, bool) {
	if o == nil || isNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *DevcloudPort) HasDescription() bool {
	if o != nil && !isNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *DevcloudPort) SetDescription(v string) {
	o.Description = &v
}

// GetInterfaceMode returns the InterfaceMode field value if set, zero value otherwise.
func (o *DevcloudPort) GetInterfaceMode() string {
	if o == nil || isNil(o.InterfaceMode) {
		var ret string
		return ret
	}
	return *o.InterfaceMode
}

// GetInterfaceModeOk returns a tuple with the InterfaceMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DevcloudPort) GetInterfaceModeOk() (*string, bool) {
	if o == nil || isNil(o.InterfaceMode) {
		return nil, false
	}
	return o.InterfaceMode, true
}

// HasInterfaceMode returns a boolean if a field has been set.
func (o *DevcloudPort) HasInterfaceMode() bool {
	if o != nil && !isNil(o.InterfaceMode) {
		return true
	}

	return false
}

// SetInterfaceMode gets a reference to the given string and assigns it to the InterfaceMode field.
func (o *DevcloudPort) SetInterfaceMode(v string) {
	o.InterfaceMode = &v
}

// GetLinkStatus returns the LinkStatus field value if set, zero value otherwise.
func (o *DevcloudPort) GetLinkStatus() string {
	if o == nil || isNil(o.LinkStatus) {
		var ret string
		return ret
	}
	return *o.LinkStatus
}

// GetLinkStatusOk returns a tuple with the LinkStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DevcloudPort) GetLinkStatusOk() (*string, bool) {
	if o == nil || isNil(o.LinkStatus) {
		return nil, false
	}
	return o.LinkStatus, true
}

// HasLinkStatus returns a boolean if a field has been set.
func (o *DevcloudPort) HasLinkStatus() bool {
	if o != nil && !isNil(o.LinkStatus) {
		return true
	}

	return false
}

// SetLinkStatus gets a reference to the given string and assigns it to the LinkStatus field.
func (o *DevcloudPort) SetLinkStatus(v string) {
	o.LinkStatus = &v
}

// GetMode returns the Mode field value if set, zero value otherwise.
func (o *DevcloudPort) GetMode() string {
	if o == nil || isNil(o.Mode) {
		var ret string
		return ret
	}
	return *o.Mode
}

// GetModeOk returns a tuple with the Mode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DevcloudPort) GetModeOk() (*string, bool) {
	if o == nil || isNil(o.Mode) {
		return nil, false
	}
	return o.Mode, true
}

// HasMode returns a boolean if a field has been set.
func (o *DevcloudPort) HasMode() bool {
	if o != nil && !isNil(o.Mode) {
		return true
	}

	return false
}

// SetMode gets a reference to the given string and assigns it to the Mode field.
func (o *DevcloudPort) SetMode(v string) {
	o.Mode = &v
}

// GetNativeVlan returns the NativeVlan field value if set, zero value otherwise.
func (o *DevcloudPort) GetNativeVlan() DevcloudPortNativeVlan {
	if o == nil || isNil(o.NativeVlan) {
		var ret DevcloudPortNativeVlan
		return ret
	}
	return *o.NativeVlan
}

// GetNativeVlanOk returns a tuple with the NativeVlan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DevcloudPort) GetNativeVlanOk() (*DevcloudPortNativeVlan, bool) {
	if o == nil || isNil(o.NativeVlan) {
		return nil, false
	}
	return o.NativeVlan, true
}

// HasNativeVlan returns a boolean if a field has been set.
func (o *DevcloudPort) HasNativeVlan() bool {
	if o != nil && !isNil(o.NativeVlan) {
		return true
	}

	return false
}

// SetNativeVlan gets a reference to the given DevcloudPortNativeVlan and assigns it to the NativeVlan field.
func (o *DevcloudPort) SetNativeVlan(v DevcloudPortNativeVlan) {
	o.NativeVlan = &v
}

// GetPort returns the Port field value if set, zero value otherwise.
func (o *DevcloudPort) GetPort() string {
	if o == nil || isNil(o.Port) {
		var ret string
		return ret
	}
	return *o.Port
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DevcloudPort) GetPortOk() (*string, bool) {
	if o == nil || isNil(o.Port) {
		return nil, false
	}
	return o.Port, true
}

// HasPort returns a boolean if a field has been set.
func (o *DevcloudPort) HasPort() bool {
	if o != nil && !isNil(o.Port) {
		return true
	}

	return false
}

// SetPort gets a reference to the given string and assigns it to the Port field.
func (o *DevcloudPort) SetPort(v string) {
	o.Port = &v
}

// GetTrunkGroups returns the TrunkGroups field value if set, zero value otherwise.
func (o *DevcloudPort) GetTrunkGroups() string {
	if o == nil || isNil(o.TrunkGroups) {
		var ret string
		return ret
	}
	return *o.TrunkGroups
}

// GetTrunkGroupsOk returns a tuple with the TrunkGroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DevcloudPort) GetTrunkGroupsOk() (*string, bool) {
	if o == nil || isNil(o.TrunkGroups) {
		return nil, false
	}
	return o.TrunkGroups, true
}

// HasTrunkGroups returns a boolean if a field has been set.
func (o *DevcloudPort) HasTrunkGroups() bool {
	if o != nil && !isNil(o.TrunkGroups) {
		return true
	}

	return false
}

// SetTrunkGroups gets a reference to the given string and assigns it to the TrunkGroups field.
func (o *DevcloudPort) SetTrunkGroups(v string) {
	o.TrunkGroups = &v
}

// GetUntaggedVlan returns the UntaggedVlan field value if set, zero value otherwise.
func (o *DevcloudPort) GetUntaggedVlan() DevcloudPortNativeVlan {
	if o == nil || isNil(o.UntaggedVlan) {
		var ret DevcloudPortNativeVlan
		return ret
	}
	return *o.UntaggedVlan
}

// GetUntaggedVlanOk returns a tuple with the UntaggedVlan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DevcloudPort) GetUntaggedVlanOk() (*DevcloudPortNativeVlan, bool) {
	if o == nil || isNil(o.UntaggedVlan) {
		return nil, false
	}
	return o.UntaggedVlan, true
}

// HasUntaggedVlan returns a boolean if a field has been set.
func (o *DevcloudPort) HasUntaggedVlan() bool {
	if o != nil && !isNil(o.UntaggedVlan) {
		return true
	}

	return false
}

// SetUntaggedVlan gets a reference to the given DevcloudPortNativeVlan and assigns it to the UntaggedVlan field.
func (o *DevcloudPort) SetUntaggedVlan(v DevcloudPortNativeVlan) {
	o.UntaggedVlan = &v
}

func (o DevcloudPort) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !isNil(o.InterfaceMode) {
		toSerialize["interface_mode"] = o.InterfaceMode
	}
	if !isNil(o.LinkStatus) {
		toSerialize["link_status"] = o.LinkStatus
	}
	if !isNil(o.Mode) {
		toSerialize["mode"] = o.Mode
	}
	if !isNil(o.NativeVlan) {
		toSerialize["native_vlan"] = o.NativeVlan
	}
	if !isNil(o.Port) {
		toSerialize["port"] = o.Port
	}
	if !isNil(o.TrunkGroups) {
		toSerialize["trunk_groups"] = o.TrunkGroups
	}
	if !isNil(o.UntaggedVlan) {
		toSerialize["untagged_vlan"] = o.UntaggedVlan
	}
	return json.Marshal(toSerialize)
}

type NullableDevcloudPort struct {
	value *DevcloudPort
	isSet bool
}

func (v NullableDevcloudPort) Get() *DevcloudPort {
	return v.value
}

func (v *NullableDevcloudPort) Set(val *DevcloudPort) {
	v.value = val
	v.isSet = true
}

func (v NullableDevcloudPort) IsSet() bool {
	return v.isSet
}

func (v *NullableDevcloudPort) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDevcloudPort(val *DevcloudPort) *NullableDevcloudPort {
	return &NullableDevcloudPort{value: val, isSet: true}
}

func (v NullableDevcloudPort) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDevcloudPort) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
