// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: quota_admin_private.proto

package pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ServiceQuotaResourceRequestPrivate with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *ServiceQuotaResourceRequestPrivate) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ServiceQuotaResourceRequestPrivate
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// ServiceQuotaResourceRequestPrivateMultiError, or nil if none found.
func (m *ServiceQuotaResourceRequestPrivate) ValidateAll() error {
	return m.validate(true)
}

func (m *ServiceQuotaResourceRequestPrivate) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ServiceName

	// no validation rules for ResourceType

	// no validation rules for CloudAccountId

	if len(errors) > 0 {
		return ServiceQuotaResourceRequestPrivateMultiError(errors)
	}

	return nil
}

// ServiceQuotaResourceRequestPrivateMultiError is an error wrapping multiple
// validation errors returned by
// ServiceQuotaResourceRequestPrivate.ValidateAll() if the designated
// constraints aren't met.
type ServiceQuotaResourceRequestPrivateMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ServiceQuotaResourceRequestPrivateMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ServiceQuotaResourceRequestPrivateMultiError) AllErrors() []error { return m }

// ServiceQuotaResourceRequestPrivateValidationError is the validation error
// returned by ServiceQuotaResourceRequestPrivate.Validate if the designated
// constraints aren't met.
type ServiceQuotaResourceRequestPrivateValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ServiceQuotaResourceRequestPrivateValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ServiceQuotaResourceRequestPrivateValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ServiceQuotaResourceRequestPrivateValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ServiceQuotaResourceRequestPrivateValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ServiceQuotaResourceRequestPrivateValidationError) ErrorName() string {
	return "ServiceQuotaResourceRequestPrivateValidationError"
}

// Error satisfies the builtin error interface
func (e ServiceQuotaResourceRequestPrivateValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sServiceQuotaResourceRequestPrivate.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ServiceQuotaResourceRequestPrivateValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ServiceQuotaResourceRequestPrivateValidationError{}

// Validate checks the field values on ServiceQuotaPrivate with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ServiceQuotaPrivate) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ServiceQuotaPrivate with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ServiceQuotaPrivateMultiError, or nil if none found.
func (m *ServiceQuotaPrivate) ValidateAll() error {
	return m.validate(true)
}

func (m *ServiceQuotaPrivate) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ServiceName

	for idx, item := range m.GetServiceResources() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ServiceQuotaPrivateValidationError{
						field:  fmt.Sprintf("ServiceResources[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ServiceQuotaPrivateValidationError{
						field:  fmt.Sprintf("ServiceResources[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ServiceQuotaPrivateValidationError{
					field:  fmt.Sprintf("ServiceResources[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ServiceQuotaPrivateMultiError(errors)
	}

	return nil
}

// ServiceQuotaPrivateMultiError is an error wrapping multiple validation
// errors returned by ServiceQuotaPrivate.ValidateAll() if the designated
// constraints aren't met.
type ServiceQuotaPrivateMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ServiceQuotaPrivateMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ServiceQuotaPrivateMultiError) AllErrors() []error { return m }

// ServiceQuotaPrivateValidationError is the validation error returned by
// ServiceQuotaPrivate.Validate if the designated constraints aren't met.
type ServiceQuotaPrivateValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ServiceQuotaPrivateValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ServiceQuotaPrivateValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ServiceQuotaPrivateValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ServiceQuotaPrivateValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ServiceQuotaPrivateValidationError) ErrorName() string {
	return "ServiceQuotaPrivateValidationError"
}

// Error satisfies the builtin error interface
func (e ServiceQuotaPrivateValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sServiceQuotaPrivate.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ServiceQuotaPrivateValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ServiceQuotaPrivateValidationError{}

// Validate checks the field values on ServiceQuotasPrivate with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ServiceQuotasPrivate) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ServiceQuotasPrivate with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ServiceQuotasPrivateMultiError, or nil if none found.
func (m *ServiceQuotasPrivate) ValidateAll() error {
	return m.validate(true)
}

func (m *ServiceQuotasPrivate) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetDefaultQuota()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ServiceQuotasPrivateValidationError{
					field:  "DefaultQuota",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ServiceQuotasPrivateValidationError{
					field:  "DefaultQuota",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDefaultQuota()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ServiceQuotasPrivateValidationError{
				field:  "DefaultQuota",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetCustomQuota()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ServiceQuotasPrivateValidationError{
					field:  "CustomQuota",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ServiceQuotasPrivateValidationError{
					field:  "CustomQuota",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCustomQuota()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ServiceQuotasPrivateValidationError{
				field:  "CustomQuota",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ServiceQuotasPrivateMultiError(errors)
	}

	return nil
}

// ServiceQuotasPrivateMultiError is an error wrapping multiple validation
// errors returned by ServiceQuotasPrivate.ValidateAll() if the designated
// constraints aren't met.
type ServiceQuotasPrivateMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ServiceQuotasPrivateMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ServiceQuotasPrivateMultiError) AllErrors() []error { return m }

// ServiceQuotasPrivateValidationError is the validation error returned by
// ServiceQuotasPrivate.Validate if the designated constraints aren't met.
type ServiceQuotasPrivateValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ServiceQuotasPrivateValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ServiceQuotasPrivateValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ServiceQuotasPrivateValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ServiceQuotasPrivateValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ServiceQuotasPrivateValidationError) ErrorName() string {
	return "ServiceQuotasPrivateValidationError"
}

// Error satisfies the builtin error interface
func (e ServiceQuotasPrivateValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sServiceQuotasPrivate.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ServiceQuotasPrivateValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ServiceQuotasPrivateValidationError{}
