/*
compute.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ProtoMachineImageSearchResponse struct for ProtoMachineImageSearchResponse
type ProtoMachineImageSearchResponse struct {
	Items []ProtoMachineImage `json:"items,omitempty"`
}

// NewProtoMachineImageSearchResponse instantiates a new ProtoMachineImageSearchResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProtoMachineImageSearchResponse() *ProtoMachineImageSearchResponse {
	this := ProtoMachineImageSearchResponse{}
	return &this
}

// NewProtoMachineImageSearchResponseWithDefaults instantiates a new ProtoMachineImageSearchResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProtoMachineImageSearchResponseWithDefaults() *ProtoMachineImageSearchResponse {
	this := ProtoMachineImageSearchResponse{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *ProtoMachineImageSearchResponse) GetItems() []ProtoMachineImage {
	if o == nil || isNil(o.Items) {
		var ret []ProtoMachineImage
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProtoMachineImageSearchResponse) GetItemsOk() ([]ProtoMachineImage, bool) {
	if o == nil || isNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *ProtoMachineImageSearchResponse) HasItems() bool {
	if o != nil && !isNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []ProtoMachineImage and assigns it to the Items field.
func (o *ProtoMachineImageSearchResponse) SetItems(v []ProtoMachineImage) {
	o.Items = v
}

func (o ProtoMachineImageSearchResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return json.Marshal(toSerialize)
}

type NullableProtoMachineImageSearchResponse struct {
	value *ProtoMachineImageSearchResponse
	isSet bool
}

func (v NullableProtoMachineImageSearchResponse) Get() *ProtoMachineImageSearchResponse {
	return v.value
}

func (v *NullableProtoMachineImageSearchResponse) Set(val *ProtoMachineImageSearchResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableProtoMachineImageSearchResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableProtoMachineImageSearchResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProtoMachineImageSearchResponse(val *ProtoMachineImageSearchResponse) *NullableProtoMachineImageSearchResponse {
	return &NullableProtoMachineImageSearchResponse{value: val, isSet: true}
}

func (v NullableProtoMachineImageSearchResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProtoMachineImageSearchResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
