/*
compute.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// InstanceServiceUpdateRequest struct for InstanceServiceUpdateRequest
type InstanceServiceUpdateRequest struct {
	Metadata *InstanceServiceUpdateRequestMetadata `json:"metadata,omitempty"`
	Spec     *ProtoInstanceSpec                    `json:"spec,omitempty"`
}

// NewInstanceServiceUpdateRequest instantiates a new InstanceServiceUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstanceServiceUpdateRequest() *InstanceServiceUpdateRequest {
	this := InstanceServiceUpdateRequest{}
	return &this
}

// NewInstanceServiceUpdateRequestWithDefaults instantiates a new InstanceServiceUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstanceServiceUpdateRequestWithDefaults() *InstanceServiceUpdateRequest {
	this := InstanceServiceUpdateRequest{}
	return &this
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *InstanceServiceUpdateRequest) GetMetadata() InstanceServiceUpdateRequestMetadata {
	if o == nil || isNil(o.Metadata) {
		var ret InstanceServiceUpdateRequestMetadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceServiceUpdateRequest) GetMetadataOk() (*InstanceServiceUpdateRequestMetadata, bool) {
	if o == nil || isNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *InstanceServiceUpdateRequest) HasMetadata() bool {
	if o != nil && !isNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given InstanceServiceUpdateRequestMetadata and assigns it to the Metadata field.
func (o *InstanceServiceUpdateRequest) SetMetadata(v InstanceServiceUpdateRequestMetadata) {
	o.Metadata = &v
}

// GetSpec returns the Spec field value if set, zero value otherwise.
func (o *InstanceServiceUpdateRequest) GetSpec() ProtoInstanceSpec {
	if o == nil || isNil(o.Spec) {
		var ret ProtoInstanceSpec
		return ret
	}
	return *o.Spec
}

// GetSpecOk returns a tuple with the Spec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceServiceUpdateRequest) GetSpecOk() (*ProtoInstanceSpec, bool) {
	if o == nil || isNil(o.Spec) {
		return nil, false
	}
	return o.Spec, true
}

// HasSpec returns a boolean if a field has been set.
func (o *InstanceServiceUpdateRequest) HasSpec() bool {
	if o != nil && !isNil(o.Spec) {
		return true
	}

	return false
}

// SetSpec gets a reference to the given ProtoInstanceSpec and assigns it to the Spec field.
func (o *InstanceServiceUpdateRequest) SetSpec(v ProtoInstanceSpec) {
	o.Spec = &v
}

func (o InstanceServiceUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !isNil(o.Spec) {
		toSerialize["spec"] = o.Spec
	}
	return json.Marshal(toSerialize)
}

type NullableInstanceServiceUpdateRequest struct {
	value *InstanceServiceUpdateRequest
	isSet bool
}

func (v NullableInstanceServiceUpdateRequest) Get() *InstanceServiceUpdateRequest {
	return v.value
}

func (v *NullableInstanceServiceUpdateRequest) Set(val *InstanceServiceUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableInstanceServiceUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableInstanceServiceUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstanceServiceUpdateRequest(val *InstanceServiceUpdateRequest) *NullableInstanceServiceUpdateRequest {
	return &NullableInstanceServiceUpdateRequest{value: val, isSet: true}
}

func (v NullableInstanceServiceUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstanceServiceUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
