/*
compute.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ProtoMachineImageDeleteRequest struct for ProtoMachineImageDeleteRequest
type ProtoMachineImageDeleteRequest struct {
	Metadata *ProtoMachineImageDeleteRequestMetadata `json:"metadata,omitempty"`
}

// NewProtoMachineImageDeleteRequest instantiates a new ProtoMachineImageDeleteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProtoMachineImageDeleteRequest() *ProtoMachineImageDeleteRequest {
	this := ProtoMachineImageDeleteRequest{}
	return &this
}

// NewProtoMachineImageDeleteRequestWithDefaults instantiates a new ProtoMachineImageDeleteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProtoMachineImageDeleteRequestWithDefaults() *ProtoMachineImageDeleteRequest {
	this := ProtoMachineImageDeleteRequest{}
	return &this
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *ProtoMachineImageDeleteRequest) GetMetadata() ProtoMachineImageDeleteRequestMetadata {
	if o == nil || isNil(o.Metadata) {
		var ret ProtoMachineImageDeleteRequestMetadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProtoMachineImageDeleteRequest) GetMetadataOk() (*ProtoMachineImageDeleteRequestMetadata, bool) {
	if o == nil || isNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *ProtoMachineImageDeleteRequest) HasMetadata() bool {
	if o != nil && !isNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given ProtoMachineImageDeleteRequestMetadata and assigns it to the Metadata field.
func (o *ProtoMachineImageDeleteRequest) SetMetadata(v ProtoMachineImageDeleteRequestMetadata) {
	o.Metadata = &v
}

func (o ProtoMachineImageDeleteRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return json.Marshal(toSerialize)
}

type NullableProtoMachineImageDeleteRequest struct {
	value *ProtoMachineImageDeleteRequest
	isSet bool
}

func (v NullableProtoMachineImageDeleteRequest) Get() *ProtoMachineImageDeleteRequest {
	return v.value
}

func (v *NullableProtoMachineImageDeleteRequest) Set(val *ProtoMachineImageDeleteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProtoMachineImageDeleteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProtoMachineImageDeleteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProtoMachineImageDeleteRequest(val *ProtoMachineImageDeleteRequest) *NullableProtoMachineImageDeleteRequest {
	return &NullableProtoMachineImageDeleteRequest{value: val, isSet: true}
}

func (v NullableProtoMachineImageDeleteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProtoMachineImageDeleteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
