/*
compute.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ProtoLoadBalancerPoolStatusMember struct for ProtoLoadBalancerPoolStatusMember
type ProtoLoadBalancerPoolStatusMember struct {
	InstanceRef *string `json:"instanceRef,omitempty"`
	Ip          *string `json:"ip,omitempty"`
}

// NewProtoLoadBalancerPoolStatusMember instantiates a new ProtoLoadBalancerPoolStatusMember object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProtoLoadBalancerPoolStatusMember() *ProtoLoadBalancerPoolStatusMember {
	this := ProtoLoadBalancerPoolStatusMember{}
	return &this
}

// NewProtoLoadBalancerPoolStatusMemberWithDefaults instantiates a new ProtoLoadBalancerPoolStatusMember object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProtoLoadBalancerPoolStatusMemberWithDefaults() *ProtoLoadBalancerPoolStatusMember {
	this := ProtoLoadBalancerPoolStatusMember{}
	return &this
}

// GetInstanceRef returns the InstanceRef field value if set, zero value otherwise.
func (o *ProtoLoadBalancerPoolStatusMember) GetInstanceRef() string {
	if o == nil || isNil(o.InstanceRef) {
		var ret string
		return ret
	}
	return *o.InstanceRef
}

// GetInstanceRefOk returns a tuple with the InstanceRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProtoLoadBalancerPoolStatusMember) GetInstanceRefOk() (*string, bool) {
	if o == nil || isNil(o.InstanceRef) {
		return nil, false
	}
	return o.InstanceRef, true
}

// HasInstanceRef returns a boolean if a field has been set.
func (o *ProtoLoadBalancerPoolStatusMember) HasInstanceRef() bool {
	if o != nil && !isNil(o.InstanceRef) {
		return true
	}

	return false
}

// SetInstanceRef gets a reference to the given string and assigns it to the InstanceRef field.
func (o *ProtoLoadBalancerPoolStatusMember) SetInstanceRef(v string) {
	o.InstanceRef = &v
}

// GetIp returns the Ip field value if set, zero value otherwise.
func (o *ProtoLoadBalancerPoolStatusMember) GetIp() string {
	if o == nil || isNil(o.Ip) {
		var ret string
		return ret
	}
	return *o.Ip
}

// GetIpOk returns a tuple with the Ip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProtoLoadBalancerPoolStatusMember) GetIpOk() (*string, bool) {
	if o == nil || isNil(o.Ip) {
		return nil, false
	}
	return o.Ip, true
}

// HasIp returns a boolean if a field has been set.
func (o *ProtoLoadBalancerPoolStatusMember) HasIp() bool {
	if o != nil && !isNil(o.Ip) {
		return true
	}

	return false
}

// SetIp gets a reference to the given string and assigns it to the Ip field.
func (o *ProtoLoadBalancerPoolStatusMember) SetIp(v string) {
	o.Ip = &v
}

func (o ProtoLoadBalancerPoolStatusMember) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.InstanceRef) {
		toSerialize["instanceRef"] = o.InstanceRef
	}
	if !isNil(o.Ip) {
		toSerialize["ip"] = o.Ip
	}
	return json.Marshal(toSerialize)
}

type NullableProtoLoadBalancerPoolStatusMember struct {
	value *ProtoLoadBalancerPoolStatusMember
	isSet bool
}

func (v NullableProtoLoadBalancerPoolStatusMember) Get() *ProtoLoadBalancerPoolStatusMember {
	return v.value
}

func (v *NullableProtoLoadBalancerPoolStatusMember) Set(val *ProtoLoadBalancerPoolStatusMember) {
	v.value = val
	v.isSet = true
}

func (v NullableProtoLoadBalancerPoolStatusMember) IsSet() bool {
	return v.isSet
}

func (v *NullableProtoLoadBalancerPoolStatusMember) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProtoLoadBalancerPoolStatusMember(val *ProtoLoadBalancerPoolStatusMember) *NullableProtoLoadBalancerPoolStatusMember {
	return &NullableProtoLoadBalancerPoolStatusMember{value: val, isSet: true}
}

func (v NullableProtoLoadBalancerPoolStatusMember) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProtoLoadBalancerPoolStatusMember) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
