/*
compute.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// LoadBalancerServiceSearch2Request struct for LoadBalancerServiceSearch2Request
type LoadBalancerServiceSearch2Request struct {
	Metadata *LoadBalancerServiceSearch2RequestMetadata `json:"metadata,omitempty"`
}

// NewLoadBalancerServiceSearch2Request instantiates a new LoadBalancerServiceSearch2Request object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoadBalancerServiceSearch2Request() *LoadBalancerServiceSearch2Request {
	this := LoadBalancerServiceSearch2Request{}
	return &this
}

// NewLoadBalancerServiceSearch2RequestWithDefaults instantiates a new LoadBalancerServiceSearch2Request object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoadBalancerServiceSearch2RequestWithDefaults() *LoadBalancerServiceSearch2Request {
	this := LoadBalancerServiceSearch2Request{}
	return &this
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *LoadBalancerServiceSearch2Request) GetMetadata() LoadBalancerServiceSearch2RequestMetadata {
	if o == nil || isNil(o.Metadata) {
		var ret LoadBalancerServiceSearch2RequestMetadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoadBalancerServiceSearch2Request) GetMetadataOk() (*LoadBalancerServiceSearch2RequestMetadata, bool) {
	if o == nil || isNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *LoadBalancerServiceSearch2Request) HasMetadata() bool {
	if o != nil && !isNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given LoadBalancerServiceSearch2RequestMetadata and assigns it to the Metadata field.
func (o *LoadBalancerServiceSearch2Request) SetMetadata(v LoadBalancerServiceSearch2RequestMetadata) {
	o.Metadata = &v
}

func (o LoadBalancerServiceSearch2Request) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return json.Marshal(toSerialize)
}

type NullableLoadBalancerServiceSearch2Request struct {
	value *LoadBalancerServiceSearch2Request
	isSet bool
}

func (v NullableLoadBalancerServiceSearch2Request) Get() *LoadBalancerServiceSearch2Request {
	return v.value
}

func (v *NullableLoadBalancerServiceSearch2Request) Set(val *LoadBalancerServiceSearch2Request) {
	v.value = val
	v.isSet = true
}

func (v NullableLoadBalancerServiceSearch2Request) IsSet() bool {
	return v.isSet
}

func (v *NullableLoadBalancerServiceSearch2Request) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoadBalancerServiceSearch2Request(val *LoadBalancerServiceSearch2Request) *NullableLoadBalancerServiceSearch2Request {
	return &NullableLoadBalancerServiceSearch2Request{value: val, isSet: true}
}

func (v NullableLoadBalancerServiceSearch2Request) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoadBalancerServiceSearch2Request) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
