/*
compute.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ProtoMachineImageSpec struct for ProtoMachineImageSpec
type ProtoMachineImageSpec struct {
	DisplayName *string `json:"displayName,omitempty"`
	Description *string `json:"description,omitempty"`
	UserName    *string `json:"userName,omitempty"`
	Icon        *string `json:"icon,omitempty"`
	// If not empty, this machine image is only compatible with the specified instance categories.
	InstanceCategories []ProtoInstanceCategory `json:"instanceCategories,omitempty"`
	// If not empty, this machine image is only compatible with the specified instance types.
	InstanceTypes   []string                     `json:"instanceTypes,omitempty"`
	Md5sum          *string                      `json:"md5sum,omitempty"`
	Sha256sum       *string                      `json:"sha256sum,omitempty"`
	Sha512sum       *string                      `json:"sha512sum,omitempty"`
	Labels          *map[string]string           `json:"labels,omitempty"`
	ImageCategories []string                     `json:"imageCategories,omitempty"`
	Components      []ProtoMachineImageComponent `json:"components,omitempty"`
	// If true, this machine image will not be returned by the MachineImageService.Search method but it can still be used to launch instances.
	Hidden           *bool   `json:"hidden,omitempty"`
	VirtualSizeBytes *string `json:"virtualSizeBytes,omitempty"`
}

// NewProtoMachineImageSpec instantiates a new ProtoMachineImageSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProtoMachineImageSpec() *ProtoMachineImageSpec {
	this := ProtoMachineImageSpec{}
	return &this
}

// NewProtoMachineImageSpecWithDefaults instantiates a new ProtoMachineImageSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProtoMachineImageSpecWithDefaults() *ProtoMachineImageSpec {
	this := ProtoMachineImageSpec{}
	return &this
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *ProtoMachineImageSpec) GetDisplayName() string {
	if o == nil || isNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProtoMachineImageSpec) GetDisplayNameOk() (*string, bool) {
	if o == nil || isNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *ProtoMachineImageSpec) HasDisplayName() bool {
	if o != nil && !isNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *ProtoMachineImageSpec) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ProtoMachineImageSpec) GetDescription() string {
	if o == nil || isNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProtoMachineImageSpec) GetDescriptionOk() (*string, bool) {
	if o == nil || isNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ProtoMachineImageSpec) HasDescription() bool {
	if o != nil && !isNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ProtoMachineImageSpec) SetDescription(v string) {
	o.Description = &v
}

// GetUserName returns the UserName field value if set, zero value otherwise.
func (o *ProtoMachineImageSpec) GetUserName() string {
	if o == nil || isNil(o.UserName) {
		var ret string
		return ret
	}
	return *o.UserName
}

// GetUserNameOk returns a tuple with the UserName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProtoMachineImageSpec) GetUserNameOk() (*string, bool) {
	if o == nil || isNil(o.UserName) {
		return nil, false
	}
	return o.UserName, true
}

// HasUserName returns a boolean if a field has been set.
func (o *ProtoMachineImageSpec) HasUserName() bool {
	if o != nil && !isNil(o.UserName) {
		return true
	}

	return false
}

// SetUserName gets a reference to the given string and assigns it to the UserName field.
func (o *ProtoMachineImageSpec) SetUserName(v string) {
	o.UserName = &v
}

// GetIcon returns the Icon field value if set, zero value otherwise.
func (o *ProtoMachineImageSpec) GetIcon() string {
	if o == nil || isNil(o.Icon) {
		var ret string
		return ret
	}
	return *o.Icon
}

// GetIconOk returns a tuple with the Icon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProtoMachineImageSpec) GetIconOk() (*string, bool) {
	if o == nil || isNil(o.Icon) {
		return nil, false
	}
	return o.Icon, true
}

// HasIcon returns a boolean if a field has been set.
func (o *ProtoMachineImageSpec) HasIcon() bool {
	if o != nil && !isNil(o.Icon) {
		return true
	}

	return false
}

// SetIcon gets a reference to the given string and assigns it to the Icon field.
func (o *ProtoMachineImageSpec) SetIcon(v string) {
	o.Icon = &v
}

// GetInstanceCategories returns the InstanceCategories field value if set, zero value otherwise.
func (o *ProtoMachineImageSpec) GetInstanceCategories() []ProtoInstanceCategory {
	if o == nil || isNil(o.InstanceCategories) {
		var ret []ProtoInstanceCategory
		return ret
	}
	return o.InstanceCategories
}

// GetInstanceCategoriesOk returns a tuple with the InstanceCategories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProtoMachineImageSpec) GetInstanceCategoriesOk() ([]ProtoInstanceCategory, bool) {
	if o == nil || isNil(o.InstanceCategories) {
		return nil, false
	}
	return o.InstanceCategories, true
}

// HasInstanceCategories returns a boolean if a field has been set.
func (o *ProtoMachineImageSpec) HasInstanceCategories() bool {
	if o != nil && !isNil(o.InstanceCategories) {
		return true
	}

	return false
}

// SetInstanceCategories gets a reference to the given []ProtoInstanceCategory and assigns it to the InstanceCategories field.
func (o *ProtoMachineImageSpec) SetInstanceCategories(v []ProtoInstanceCategory) {
	o.InstanceCategories = v
}

// GetInstanceTypes returns the InstanceTypes field value if set, zero value otherwise.
func (o *ProtoMachineImageSpec) GetInstanceTypes() []string {
	if o == nil || isNil(o.InstanceTypes) {
		var ret []string
		return ret
	}
	return o.InstanceTypes
}

// GetInstanceTypesOk returns a tuple with the InstanceTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProtoMachineImageSpec) GetInstanceTypesOk() ([]string, bool) {
	if o == nil || isNil(o.InstanceTypes) {
		return nil, false
	}
	return o.InstanceTypes, true
}

// HasInstanceTypes returns a boolean if a field has been set.
func (o *ProtoMachineImageSpec) HasInstanceTypes() bool {
	if o != nil && !isNil(o.InstanceTypes) {
		return true
	}

	return false
}

// SetInstanceTypes gets a reference to the given []string and assigns it to the InstanceTypes field.
func (o *ProtoMachineImageSpec) SetInstanceTypes(v []string) {
	o.InstanceTypes = v
}

// GetMd5sum returns the Md5sum field value if set, zero value otherwise.
func (o *ProtoMachineImageSpec) GetMd5sum() string {
	if o == nil || isNil(o.Md5sum) {
		var ret string
		return ret
	}
	return *o.Md5sum
}

// GetMd5sumOk returns a tuple with the Md5sum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProtoMachineImageSpec) GetMd5sumOk() (*string, bool) {
	if o == nil || isNil(o.Md5sum) {
		return nil, false
	}
	return o.Md5sum, true
}

// HasMd5sum returns a boolean if a field has been set.
func (o *ProtoMachineImageSpec) HasMd5sum() bool {
	if o != nil && !isNil(o.Md5sum) {
		return true
	}

	return false
}

// SetMd5sum gets a reference to the given string and assigns it to the Md5sum field.
func (o *ProtoMachineImageSpec) SetMd5sum(v string) {
	o.Md5sum = &v
}

// GetSha256sum returns the Sha256sum field value if set, zero value otherwise.
func (o *ProtoMachineImageSpec) GetSha256sum() string {
	if o == nil || isNil(o.Sha256sum) {
		var ret string
		return ret
	}
	return *o.Sha256sum
}

// GetSha256sumOk returns a tuple with the Sha256sum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProtoMachineImageSpec) GetSha256sumOk() (*string, bool) {
	if o == nil || isNil(o.Sha256sum) {
		return nil, false
	}
	return o.Sha256sum, true
}

// HasSha256sum returns a boolean if a field has been set.
func (o *ProtoMachineImageSpec) HasSha256sum() bool {
	if o != nil && !isNil(o.Sha256sum) {
		return true
	}

	return false
}

// SetSha256sum gets a reference to the given string and assigns it to the Sha256sum field.
func (o *ProtoMachineImageSpec) SetSha256sum(v string) {
	o.Sha256sum = &v
}

// GetSha512sum returns the Sha512sum field value if set, zero value otherwise.
func (o *ProtoMachineImageSpec) GetSha512sum() string {
	if o == nil || isNil(o.Sha512sum) {
		var ret string
		return ret
	}
	return *o.Sha512sum
}

// GetSha512sumOk returns a tuple with the Sha512sum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProtoMachineImageSpec) GetSha512sumOk() (*string, bool) {
	if o == nil || isNil(o.Sha512sum) {
		return nil, false
	}
	return o.Sha512sum, true
}

// HasSha512sum returns a boolean if a field has been set.
func (o *ProtoMachineImageSpec) HasSha512sum() bool {
	if o != nil && !isNil(o.Sha512sum) {
		return true
	}

	return false
}

// SetSha512sum gets a reference to the given string and assigns it to the Sha512sum field.
func (o *ProtoMachineImageSpec) SetSha512sum(v string) {
	o.Sha512sum = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *ProtoMachineImageSpec) GetLabels() map[string]string {
	if o == nil || isNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return *o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProtoMachineImageSpec) GetLabelsOk() (*map[string]string, bool) {
	if o == nil || isNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *ProtoMachineImageSpec) HasLabels() bool {
	if o != nil && !isNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *ProtoMachineImageSpec) SetLabels(v map[string]string) {
	o.Labels = &v
}

// GetImageCategories returns the ImageCategories field value if set, zero value otherwise.
func (o *ProtoMachineImageSpec) GetImageCategories() []string {
	if o == nil || isNil(o.ImageCategories) {
		var ret []string
		return ret
	}
	return o.ImageCategories
}

// GetImageCategoriesOk returns a tuple with the ImageCategories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProtoMachineImageSpec) GetImageCategoriesOk() ([]string, bool) {
	if o == nil || isNil(o.ImageCategories) {
		return nil, false
	}
	return o.ImageCategories, true
}

// HasImageCategories returns a boolean if a field has been set.
func (o *ProtoMachineImageSpec) HasImageCategories() bool {
	if o != nil && !isNil(o.ImageCategories) {
		return true
	}

	return false
}

// SetImageCategories gets a reference to the given []string and assigns it to the ImageCategories field.
func (o *ProtoMachineImageSpec) SetImageCategories(v []string) {
	o.ImageCategories = v
}

// GetComponents returns the Components field value if set, zero value otherwise.
func (o *ProtoMachineImageSpec) GetComponents() []ProtoMachineImageComponent {
	if o == nil || isNil(o.Components) {
		var ret []ProtoMachineImageComponent
		return ret
	}
	return o.Components
}

// GetComponentsOk returns a tuple with the Components field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProtoMachineImageSpec) GetComponentsOk() ([]ProtoMachineImageComponent, bool) {
	if o == nil || isNil(o.Components) {
		return nil, false
	}
	return o.Components, true
}

// HasComponents returns a boolean if a field has been set.
func (o *ProtoMachineImageSpec) HasComponents() bool {
	if o != nil && !isNil(o.Components) {
		return true
	}

	return false
}

// SetComponents gets a reference to the given []ProtoMachineImageComponent and assigns it to the Components field.
func (o *ProtoMachineImageSpec) SetComponents(v []ProtoMachineImageComponent) {
	o.Components = v
}

// GetHidden returns the Hidden field value if set, zero value otherwise.
func (o *ProtoMachineImageSpec) GetHidden() bool {
	if o == nil || isNil(o.Hidden) {
		var ret bool
		return ret
	}
	return *o.Hidden
}

// GetHiddenOk returns a tuple with the Hidden field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProtoMachineImageSpec) GetHiddenOk() (*bool, bool) {
	if o == nil || isNil(o.Hidden) {
		return nil, false
	}
	return o.Hidden, true
}

// HasHidden returns a boolean if a field has been set.
func (o *ProtoMachineImageSpec) HasHidden() bool {
	if o != nil && !isNil(o.Hidden) {
		return true
	}

	return false
}

// SetHidden gets a reference to the given bool and assigns it to the Hidden field.
func (o *ProtoMachineImageSpec) SetHidden(v bool) {
	o.Hidden = &v
}

// GetVirtualSizeBytes returns the VirtualSizeBytes field value if set, zero value otherwise.
func (o *ProtoMachineImageSpec) GetVirtualSizeBytes() string {
	if o == nil || isNil(o.VirtualSizeBytes) {
		var ret string
		return ret
	}
	return *o.VirtualSizeBytes
}

// GetVirtualSizeBytesOk returns a tuple with the VirtualSizeBytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProtoMachineImageSpec) GetVirtualSizeBytesOk() (*string, bool) {
	if o == nil || isNil(o.VirtualSizeBytes) {
		return nil, false
	}
	return o.VirtualSizeBytes, true
}

// HasVirtualSizeBytes returns a boolean if a field has been set.
func (o *ProtoMachineImageSpec) HasVirtualSizeBytes() bool {
	if o != nil && !isNil(o.VirtualSizeBytes) {
		return true
	}

	return false
}

// SetVirtualSizeBytes gets a reference to the given string and assigns it to the VirtualSizeBytes field.
func (o *ProtoMachineImageSpec) SetVirtualSizeBytes(v string) {
	o.VirtualSizeBytes = &v
}

func (o ProtoMachineImageSpec) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.DisplayName) {
		toSerialize["displayName"] = o.DisplayName
	}
	if !isNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !isNil(o.UserName) {
		toSerialize["userName"] = o.UserName
	}
	if !isNil(o.Icon) {
		toSerialize["icon"] = o.Icon
	}
	if !isNil(o.InstanceCategories) {
		toSerialize["instanceCategories"] = o.InstanceCategories
	}
	if !isNil(o.InstanceTypes) {
		toSerialize["instanceTypes"] = o.InstanceTypes
	}
	if !isNil(o.Md5sum) {
		toSerialize["md5sum"] = o.Md5sum
	}
	if !isNil(o.Sha256sum) {
		toSerialize["sha256sum"] = o.Sha256sum
	}
	if !isNil(o.Sha512sum) {
		toSerialize["sha512sum"] = o.Sha512sum
	}
	if !isNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !isNil(o.ImageCategories) {
		toSerialize["imageCategories"] = o.ImageCategories
	}
	if !isNil(o.Components) {
		toSerialize["components"] = o.Components
	}
	if !isNil(o.Hidden) {
		toSerialize["hidden"] = o.Hidden
	}
	if !isNil(o.VirtualSizeBytes) {
		toSerialize["virtualSizeBytes"] = o.VirtualSizeBytes
	}
	return json.Marshal(toSerialize)
}

type NullableProtoMachineImageSpec struct {
	value *ProtoMachineImageSpec
	isSet bool
}

func (v NullableProtoMachineImageSpec) Get() *ProtoMachineImageSpec {
	return v.value
}

func (v *NullableProtoMachineImageSpec) Set(val *ProtoMachineImageSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableProtoMachineImageSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableProtoMachineImageSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProtoMachineImageSpec(val *ProtoMachineImageSpec) *NullableProtoMachineImageSpec {
	return &NullableProtoMachineImageSpec{value: val, isSet: true}
}

func (v NullableProtoMachineImageSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProtoMachineImageSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
