/*
compute.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// InstanceServiceUpdate2Request struct for InstanceServiceUpdate2Request
type InstanceServiceUpdate2Request struct {
	Metadata *InstanceServiceUpdate2RequestMetadata `json:"metadata,omitempty"`
	Spec     *ProtoInstanceSpec                     `json:"spec,omitempty"`
}

// NewInstanceServiceUpdate2Request instantiates a new InstanceServiceUpdate2Request object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstanceServiceUpdate2Request() *InstanceServiceUpdate2Request {
	this := InstanceServiceUpdate2Request{}
	return &this
}

// NewInstanceServiceUpdate2RequestWithDefaults instantiates a new InstanceServiceUpdate2Request object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstanceServiceUpdate2RequestWithDefaults() *InstanceServiceUpdate2Request {
	this := InstanceServiceUpdate2Request{}
	return &this
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *InstanceServiceUpdate2Request) GetMetadata() InstanceServiceUpdate2RequestMetadata {
	if o == nil || isNil(o.Metadata) {
		var ret InstanceServiceUpdate2RequestMetadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceServiceUpdate2Request) GetMetadataOk() (*InstanceServiceUpdate2RequestMetadata, bool) {
	if o == nil || isNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *InstanceServiceUpdate2Request) HasMetadata() bool {
	if o != nil && !isNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given InstanceServiceUpdate2RequestMetadata and assigns it to the Metadata field.
func (o *InstanceServiceUpdate2Request) SetMetadata(v InstanceServiceUpdate2RequestMetadata) {
	o.Metadata = &v
}

// GetSpec returns the Spec field value if set, zero value otherwise.
func (o *InstanceServiceUpdate2Request) GetSpec() ProtoInstanceSpec {
	if o == nil || isNil(o.Spec) {
		var ret ProtoInstanceSpec
		return ret
	}
	return *o.Spec
}

// GetSpecOk returns a tuple with the Spec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceServiceUpdate2Request) GetSpecOk() (*ProtoInstanceSpec, bool) {
	if o == nil || isNil(o.Spec) {
		return nil, false
	}
	return o.Spec, true
}

// HasSpec returns a boolean if a field has been set.
func (o *InstanceServiceUpdate2Request) HasSpec() bool {
	if o != nil && !isNil(o.Spec) {
		return true
	}

	return false
}

// SetSpec gets a reference to the given ProtoInstanceSpec and assigns it to the Spec field.
func (o *InstanceServiceUpdate2Request) SetSpec(v ProtoInstanceSpec) {
	o.Spec = &v
}

func (o InstanceServiceUpdate2Request) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !isNil(o.Spec) {
		toSerialize["spec"] = o.Spec
	}
	return json.Marshal(toSerialize)
}

type NullableInstanceServiceUpdate2Request struct {
	value *InstanceServiceUpdate2Request
	isSet bool
}

func (v NullableInstanceServiceUpdate2Request) Get() *InstanceServiceUpdate2Request {
	return v.value
}

func (v *NullableInstanceServiceUpdate2Request) Set(val *InstanceServiceUpdate2Request) {
	v.value = val
	v.isSet = true
}

func (v NullableInstanceServiceUpdate2Request) IsSet() bool {
	return v.isSet
}

func (v *NullableInstanceServiceUpdate2Request) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstanceServiceUpdate2Request(val *InstanceServiceUpdate2Request) *NullableInstanceServiceUpdate2Request {
	return &NullableInstanceServiceUpdate2Request{value: val, isSet: true}
}

func (v NullableInstanceServiceUpdate2Request) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstanceServiceUpdate2Request) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
