#!/usr/bin/env sh
if !(git diff --cached --quiet -- ./idcs_portal); then
    echo 'Files changed on idcs_portal, running pre-commit for it'
    . "$(dirname -- "$0")/_/husky.sh"
    cd ./idcs_portal && node ./copyright/checkCopyright.js && npm run lint && npm run test:husky
else
    echo 'No changes on idcs_portal, skip pre-commit for it'
fi


