{{- if .DbSeedEnabled }}

INSERT INTO public.addonversion (addonversion_name, name, version, lifecyclestate_id, admin_only, install_type, artifact_repo, default_addonargs, tags, onbuild, addonversion_type) VALUES ('calico-operator-3.28.2', 'calico-operator', '3.28.2', 1, true, 'kubectl-replace', 's3://calico-operator-3282-1.template', NULL, NULL, true, 'kubernetes');
INSERT INTO public.addonversion (addonversion_name, name, version, lifecyclestate_id, admin_only, install_type, artifact_repo, default_addonargs, tags, onbuild, addonversion_type) VALUES ('kube-proxy-1.27.1', 'kube-proxy', '1.27.1', 1, true, 'kubectl-apply', 's3://kube-proxy-k1271-1.template', NULL, NULL, true, 'kubernetes');
INSERT INTO public.addonversion (addonversion_name, name, version, lifecyclestate_id, admin_only, install_type, artifact_repo, default_addonargs, tags, onbuild, addonversion_type) VALUES ('coredns-1.7.1', 'coredns', '1.7.1', 1, true, 'kubectl-apply', 's3://coredns-171-k1271-1.template', NULL, NULL, true, 'kubernetes');
INSERT INTO public.addonversion (addonversion_name, name, version, lifecyclestate_id, admin_only, install_type, artifact_repo, default_addonargs, tags, onbuild, addonversion_type) VALUES ('calico-operator-3.26.0', 'calico-operator', '3.26.0', 1, true, 'kubectl-replace', 's3://calico-operator-3260-k1271-1.template', NULL, NULL, true, 'kubernetes');
INSERT INTO public.addonversion (addonversion_name, name, version, lifecyclestate_id, admin_only, install_type, artifact_repo, default_addonargs, tags, onbuild, addonversion_type) VALUES ('calico-config-3.26.0', 'calico-config', '3.26.0', 1, true, 'kubectl-apply', 's3://calico-config-3260-k1271-1.template', NULL, NULL, true, 'kubernetes');
INSERT INTO public.addonversion (addonversion_name, name, version, lifecyclestate_id, admin_only, install_type, artifact_repo, default_addonargs, tags, onbuild, addonversion_type) VALUES ('konnectivity-agent-0.0.0', 'konnectivity-agent', '0.0.0', 1, true, 'kubectl-apply', 's3://konnectivity-agent.template', NULL, NULL, true, 'kubernetes');
INSERT INTO public.addonversion (addonversion_name, name, version, lifecyclestate_id, admin_only, install_type, artifact_repo, default_addonargs, tags, onbuild, addonversion_type) VALUES ('kube-proxy-1.27.5', 'kube-proxy', '1.27.1', 1, true, 'kubectl-apply', 's3://kube-proxy-k1275-1.template', NULL, NULL, true, 'kubernetes');
INSERT INTO public.addonversion (addonversion_name, name, version, lifecyclestate_id, admin_only, install_type, artifact_repo, default_addonargs, tags, onbuild, addonversion_type) VALUES ('kube-proxy-1.27.6', 'kube-proxy', '1.27.6', 1, true, 'kubectl-apply', 's3://kube-proxy-k1275-1.template', NULL, NULL, true, 'kubernetes');
INSERT INTO public.addonversion (addonversion_name, name, version, lifecyclestate_id, admin_only, install_type, artifact_repo, default_addonargs, tags, onbuild, addonversion_type) VALUES ('kube-proxy-1.27.7', 'kube-proxy', '1.27.7', 1, true, 'kubectl-apply', 's3://kube-proxy-1277-1.template', NULL, NULL, true, 'kubernetes');
INSERT INTO public.addonversion (addonversion_name, name, version, lifecyclestate_id, admin_only, install_type, artifact_repo, default_addonargs, tags, onbuild, addonversion_type) VALUES ('kube-proxy-1.28.3', 'kube-proxy', '1.28.3', 1, true, 'kubectl-apply', 's3://kube-proxy-1283-1.template', NULL, NULL, true, 'kubernetes');
INSERT INTO public.addonversion (addonversion_name, name, version, lifecyclestate_id, admin_only, install_type, artifact_repo, default_addonargs, tags, onbuild, addonversion_type) VALUES ('coredns-1.11.1', 'coredns', '1.11.1', 1, true, 'kubectl-apply', 's3://coredns-1111-1.template', NULL, NULL, true, 'kubernetes');
INSERT INTO public.addonversion (addonversion_name, name, version, lifecyclestate_id, admin_only, install_type, artifact_repo, default_addonargs, tags, onbuild, addonversion_type) VALUES ('calico-config-3.26.3', 'calico-config', '3.26.3', 1, true, 'kubectl-apply', 's3://calico-config-3263-1.template', NULL, NULL, true, 'kubernetes');
INSERT INTO public.addonversion (addonversion_name, name, version, lifecyclestate_id, admin_only, install_type, artifact_repo, default_addonargs, tags, onbuild, addonversion_type) VALUES ('konnectivity-agent-0.1.4', 'konnectivity-agent', '0.1.4', 1, true, 'kubectl-apply', 's3://konnectivity-agent-014-1.template', NULL, NULL, true, 'kubernetes');
INSERT INTO public.addonversion (addonversion_name, name, version, lifecyclestate_id, admin_only, install_type, artifact_repo, default_addonargs, tags, onbuild, addonversion_type) VALUES ('konnectivity-agent-0.1.6', 'konnectivity-agent', '0.1.6', 1, true, 'kubectl-apply', 's3://konnectivity-agent-016-1.template', NULL, NULL, true, 'kubernetes');
INSERT INTO public.addonversion (addonversion_name, name, version, lifecyclestate_id, admin_only, install_type, artifact_repo, default_addonargs, tags, onbuild, addonversion_type) VALUES ('calico-operator-3.25.2', 'calico-operator', '3.25.2', 1, true, 'kubectl-replace', 's3://calico-operator-3252-1.template', NULL, NULL, true, 'kubernetes');
INSERT INTO public.addonversion (addonversion_name, name, version, lifecyclestate_id, admin_only, install_type, artifact_repo, default_addonargs, tags, onbuild, addonversion_type) VALUES ('kube-proxy-1.27.8', 'kube-proxy', '1.27.8', 1, true, 'kubectl-apply', 's3://kube-proxy-1278-1.template', NULL, NULL, true, 'kubernetes');
INSERT INTO public.addonversion (addonversion_name, name, version, lifecyclestate_id, admin_only, install_type, artifact_repo, default_addonargs, tags, onbuild, addonversion_type) VALUES ('kube-proxy-1.28.4', 'kube-proxy', '1.28.4', 1, true, 'kubectl-apply', 's3://kube-proxy-1284-1.template', NULL, NULL, true, 'kubernetes');
INSERT INTO public.addonversion (addonversion_name, name, version, lifecyclestate_id, admin_only, install_type, artifact_repo, default_addonargs, tags, onbuild, addonversion_type) VALUES ('kube-proxy-1.24.17', 'kube-proxy', '1.24.17', 1, true, 'kubectl-apply', 's3://kube-proxy-12417-1.template', NULL, NULL, true, 'kubernetes');
INSERT INTO public.addonversion (addonversion_name, name, version, lifecyclestate_id, admin_only, install_type, artifact_repo, default_addonargs, tags, onbuild, addonversion_type) VALUES ('kube-proxy-1.25.16', 'kube-proxy', '1.25.16', 1, true, 'kubectl-apply', 's3://kube-proxy-12516-1.template', NULL, NULL, true, 'kubernetes');
INSERT INTO public.addonversion (addonversion_name, name, version, lifecyclestate_id, admin_only, install_type, artifact_repo, default_addonargs, tags, onbuild, addonversion_type) VALUES ('kube-proxy-1.27.9', 'kube-proxy', '1.27.9', 1, true, 'kubectl-apply', 's3://kube-proxy-1279-1.template', NULL, NULL, true, 'kubernetes');
INSERT INTO public.addonversion (addonversion_name, name, version, lifecyclestate_id, admin_only, install_type, artifact_repo, default_addonargs, tags, onbuild, addonversion_type) VALUES ('kube-proxy-1.28.5', 'kube-proxy', '1.28.5', 1, true, 'kubectl-apply', 's3://kube-proxy-1285-1.template', NULL, NULL, true, 'kubernetes');
INSERT INTO public.addonversion (addonversion_name, name, version, lifecyclestate_id, admin_only, install_type, artifact_repo, default_addonargs, tags, onbuild, addonversion_type) VALUES ('kube-proxy-1.26.13', 'kube-proxy', '1.26.13', 1, true, 'kubectl-apply', 's3://kube-proxy-12613-1.template', NULL, NULL, true, 'kubernetes');
INSERT INTO public.addonversion (addonversion_name, name, version, lifecyclestate_id, admin_only, install_type, artifact_repo, default_addonargs, tags, onbuild, addonversion_type) VALUES ('kube-proxy-1.30.3', 'kube-proxy', '1.30.3', 1, true, 'kubectl-apply', 's3://kube-proxy-1303-1.template', NULL, NULL, true, 'kubernetes');
INSERT INTO public.addonversion (addonversion_name, name, version, lifecyclestate_id, admin_only, install_type, artifact_repo, default_addonargs, tags, onbuild, addonversion_type) VALUES ('kube-proxy-1.31.3', 'kube-proxy', '1.31.3', 1, true, 'kubectl-apply', 's3://kube-proxy-1313-1.template', NULL, NULL, true, 'kubernetes');
INSERT INTO public.addonversion (addonversion_name, name, version, lifecyclestate_id, admin_only, install_type, artifact_repo, default_addonargs, tags, onbuild, addonversion_type) VALUES ('calico-operator-3.27.2', 'calico-operator', '3.27.2', 1, true, 'kubectl-replace', 's3://calico-operator-3272-1.template', NULL, NULL, true, 'kubernetes');
INSERT into public.addonversion (addonversion_name, name, version, lifecyclestate_id, admin_only, install_type, artifact_repo, default_addonargs, tags, onbuild, addonversion_type) values ('calico-operator-3.29.1', 'calico-operator', '3.29.1', 1, true, 'kubectl-replace', 's3://calico-operator-3291-1.template', NULL, NULL, true, 'kubernetes');
INSERT INTO public.addonversion (addonversion_name, name, version, lifecyclestate_id, admin_only, install_type, artifact_repo, default_addonargs, tags, onbuild, addonversion_type) VALUES ('calico-config-general', 'calico-config', 'general', 1, true, 'kubectl-apply', 's3://calico-config-general-1.template', NULL, NULL, true, 'kubernetes');
INSERT INTO public.addonversion (addonversion_name, name, version, lifecyclestate_id, admin_only, install_type, artifact_repo, default_addonargs, tags, onbuild, addonversion_type) VALUES ('konnectivity-agent-0.1.7', 'konnectivity-agent', '0.1.7', 1, true, 'kubectl-apply', 's3://konnectivity-agent-017-1.template', NULL, NULL, true, 'kubernetes');
INSERT INTO public.addonversion (addonversion_name, name, version, lifecyclestate_id, admin_only, install_type, artifact_repo, default_addonargs, tags, onbuild, addonversion_type) VALUES ('kube-proxy-1.27.11', 'kube-proxy', '1.27.11', 1, true, 'kubectl-apply', 's3://kube-proxy-12711-1.template', NULL, NULL, true, 'kubernetes');
INSERT INTO public.addonversion (addonversion_name, name, version, lifecyclestate_id, admin_only, install_type, artifact_repo, default_addonargs, tags, onbuild, addonversion_type) VALUES ('kube-proxy-1.28.7', 'kube-proxy', '1.28.7', 1, true, 'kubectl-apply', 's3://kube-proxy-1287-1.template', NULL, NULL, true, 'kubernetes');
INSERT INTO public.addonversion (addonversion_name, name, version, lifecyclestate_id, admin_only, install_type, artifact_repo, default_addonargs, tags, onbuild, addonversion_type) VALUES ('kube-proxy-1.29.2', 'kube-proxy', '1.29.2', 1, true, 'kubectl-apply', 's3://kube-proxy-1292-1.template', NULL, NULL, true, 'kubernetes');
INSERT INTO public.addonversion (addonversion_name, name, version, lifecyclestate_id, admin_only, install_type, artifact_repo, default_addonargs, tags, onbuild, addonversion_type) VALUES ('weka-fs-plugin-2.3.4', 'weka-fs-plugin', '2.3.4', 1, true, 'helm', 'csi-wekafsplugin/v2.3.4', NULL, NULL, false, 'weka');
INSERT INTO public.addonversion (addonversion_name, name, version, lifecyclestate_id, admin_only, install_type, artifact_repo, default_addonargs, tags, onbuild, addonversion_type) Values ('weka-fs-plugin-2.5.0', 'weka-fs-plugin', '2.5.0', 1, true, 'helm', 'csi-wekafsplugin/v2.5.0', NULL, NULL, false, 'weka');
INSERT INTO public.addonversion (addonversion_name, name, version, lifecyclestate_id, admin_only, install_type, artifact_repo, default_addonargs, tags, onbuild, addonversion_type) VALUES ('weka-storageclass-0.0.0', 'weka-storageclass', '0.0.0', 1, true, 'kubectl-apply', 's3://weka-storageclass-1287-1.template', NULL, NULL, false, 'weka');




{{- end }}