# Makefile for Sphinx documentation

SHELL := /bin/bash

PY_VERSION ?= 3.8

html:
	make -C source html

clean:
	make -C source clean

guide:
	make -C source guide

tut:
	make -C source tut

tutdemo:
	make -C source tutdemo

tutclean:
	make -C source tutclean

help:
	make -C source help
