// INTEL CONFIDENTIAL
// Copyright (C) 2023 Intel Corporation
package client

// Ideally we should not map any error codes.
// This applies more for first party and second party products.
// However, Aria has many error codes, too many and is third party.
// So, we can map these error codes defined at the client level to more applies to a concept within the consumer
// of the client. For example, we can map, failed to create service to failed to sync product family.
// However, the actual error is never lost and is always returned along with a mapped error.
const (
	FailedToGetAllAcctPlans                    = "FAILED_TO_GET_ALL_ACCT_PLANS"
	FailedToGetAcctPlans                       = "FAILED_TO_GET_ALL_ACCT_PLANS"
	FailedToCreateAriaServiceError             = "FAILED_TO_CREATE_SERVICE"
	FailedToUpdateAriaServiceError             = "FAILED_TO_UPDATE_SERVICE"
	FailedToCreateOrUpdateAriaServiceError     = "FAILED_TO_CREATE_OR_UPDATE_SERVICE"
	FailedToGetUsageUnitTypesError             = "FAILED_TO_GET_USAGE_UNIT_TYPES"
	FailedToGetUsageTypesError                 = "FAILED_TO_GET_USAGE_TYPES"
	FailedToGetServiceDetailsError             = "FAILED_TO_GET_SERVICE_DETAILS"
	FailedToCreatePlanError                    = "FAILED_TO_CREATE_PLAN"
	FailedToEditPlanError                      = "FAILED_TO_EDIT_PLAN"
	FailedToGetPlansError                      = "FAILED_TO_GET_PLANS"
	FailedToGetClientPlansAllError             = "FAILED_TO_GET_CLIENT_PLANS_ALL"
	FailedToGetInvoiceDetailsError             = "FAILED_TO_GET_INVOICE_DETAILS"
	FailedToGetStatementForInvoice             = "FAILED_TO_GET_STATEMENT_FOR_INVOICE"
	FailedToGetClientPlanDetailsError          = "FAILED_TO_GET_CLIENT_PLAN_DETAILS_ALL"
	FailedToGetClientPlanServiceRatesError     = "FAILED_TO_GET_CLIENT_PLAN_SERVICE_RATES"
	FailedToDeletePlansError                   = "FAILED_TO_DELETE_PLANS"
	FailedToDeactivatePlanError                = "FAILED_TO_DEACTIVATE_PLAN"
	FailedToCreateAriaAccountError             = "FAILED_TO_CREATE_ACCOUNT"
	FailedToGetAriaAccountDetailsAllError      = "FAILED_TO_GET_ACCOUNT_DETAILS_ALL"
	FailedToCreateCloudCreditError             = "FAILED_TO_CREATE_CREDIT"
	FailedToGetUnappliedServiceCreditsError    = "FAILED_TO_GET_CLOUD_CREDIT_DETAILS_ALL"
	FailedToGetPaymentMethodsAllError          = "FAILED_TO_GET_PAYMENT_METHODS"
	FailedToRemovePaymentMethodAllError        = "FAILED_TO_REMOVE_PAYMENT_METHOD"
	FailedToAuthorizeElectronicPaymentError    = "FAILED_TO_AUTHORIZE_ELECTRONIC_PAYMENT_METHOD"
	FailedToAssignPlanToAccount                = "FAILED_TO_ASSIGN_PLAN_TO_ACCOUNT"
	FailedToAssignCollectionsAccountGroup      = "FAILED_TO_ASSIGN_COLLECTIONS_ACCOUNT_GROUP"
	FailedToUpdateAccountBillingGroup          = "FAILED_TO_UPDATE_ACCOUNT_BILLING_GROUP"
	FailedToCreateUsageTypeError               = "FAILED_TO_CREATE_USAGE_TYPE"
	FailedToUpdateUsageTypeError               = "FAILED_TO_UPDATE_USAGE_TYPE"
	FailedToGetUsageTypeDetailsError           = "FAILED_TO_GET_USAGE_TYPE_DETAILS"
	FailedToGetPromoPlanSetsError              = "FAILED_TO_GET_PROMO_PLAN_SETS"
	FailedToGetPromoPlanSetDetails             = "FAILED_TO_GET_PROMO_PLAN_SET_DETAILS"
	FailedToCreatePromoPlanSetError            = "FAILED_TO_CREATE_PROMO_PLAN_SET"
	FailedToUpdatePlanSetError                 = "FAILED_TO_UPDATE_PLAN_SET"
	FailedToGetPromotionsError                 = "FAILED_TO_GET_PROMOTIONS"
	FailedToCreatePromotionError               = "FAILED_TO_CREATE_PROMOTION"
	FailedToCreateOREditPlanError              = "FAILED_TO_CREATE_OR_EDIT_PLAN"
	FailedToCreateOrUpdateUsageTypeError       = "FAILED_TO_CREATE_OR_UPDATE_USAGE_TYPE"
	FailedToSetSession                         = "FAILED_TO_SET_SESSION"
	FailedToGetAcctNoFromUserId                = "FAILED_TO_GET_ACCOUNT_NUMBER_FROM_USER_ID"
	FailedToCreateAriaBulkUsageRecordError     = "FAILED_TO_CREATE_BULK_USAGE_RECORD"
	FailedToCreateAriaUsageRecordError         = "FAILED_TO_CREATE_USAGE_RECORD"
	FailedToGetAriaCloudCreditDetailsAllError  = "FAILED_TO_GET_CLOUD_CREDIT_DETAILS_ALL"
	FailedToSetAccountNotifyTemplateGroupError = "FAILED_TO_SET_ACCOUNT_NOTIFY_TEMPLATE_GROUP"
	FailedToUpdateAccount                      = "FAILED_TO_UPDATE_ACCOUNT"
	FailedToUpdateAccountStatus                = "FAILED_TO_UPDATE_ACCOUNT_STATUS"
	FailedToUpdateAccountError                 = "FAILED_TO_UPDATE_ACCOUNT"
	FailedToCreateBillingGroup                 = "FAILED_TO_CREATE_BILLING_GROUP"
	FailedToCreateDunningGroup                 = "FAILED_TO_CREATE_DUNNING_GROUP"
	FailedToGetAccountCreditsError             = "FAILED_TO_GET_ACCOUNT_CREDITS"
	FailedToGetCreditDetailsError              = "FAILED_TO_GET_CREDIT_DETAILS"
	FailedToGetBillingGroup                    = "FAILED_TO_GET_BILLING_GROUP"
	FailedToGetDunningGroup                    = "FAILED_TO_GET_DUNNING_GROUP"
	FailedToGetInvoiceHistory                  = "FAILED_TO_GET_INVOICE_HISTORY"
	FailedToManagePendingInvoice               = "FAILED_TO_MANAGE_PENDING_INVOICE"
	FailedToGetPendingInvoiceNo                = "FAILED_TO_GET_PENDING_INVOICE_NO"
	FailedToGetUnbilledUsageSummary            = "FAILED_TO_GET_UNBILLED_USAGE_SUMMARY"
	FailedToGetUsageSummaryByType              = "FAILED_TO_GET_USAGE_SUMMARY_BY_TYPE"
	FailedToGetUsageHistory                    = "FAILED_TO_GET_USAGE_HISTORY"
	FailedToGetAcctHierarchyDetails            = "FAILED_TO_GET_ACCOUNT_HIERARCHY_DETAILS"
	FailedToGetAccountNotificationDetailsError = "FAILED_TO_GET_ACCOUNT_NOTIFICATION_DETAILS"
	FailedToUpdateAccountContact               = "FAILED_TO_UPDATE_ACCOUNT_CONTACT"
	FailedToApplyServiceCredit                 = "FAILED_TO_APPLY_SERVICE_CREDIT"
)
